# Generated by Django 5.2.4 on 2025-07-06 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_auto_20250705_1843"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст жалобы:")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Когда создана жалоба",
                    ),
                ),
                (
                    "flat",
                    models.ForeignKey(
                        help_text="Квартира, на которую пожаловались:",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.flat",
                        verbose_name="Квартира",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, подавший жалобу",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
