# Generated by Django 5.2.4 on 2025-07-10 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_flat_liked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто лайкнул",
            ),
        ),
    ]
