# Generated by Django 5.2.4 on 2025-07-10 16:55
import phonenumbers
from phonenumbers import PhoneNumberFormat

from django.db import migrations



def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
                if phonenumbers.is_valid_number(parsed_number):
                    formatted_number = phonenumbers.format_number(parsed_number, PhoneNumberFormat.E164)
                    flat.owner_pure_phone = formatted_number
                    flat.save()
            except phonenumbers.NumberParseException:
                continue


def reverse_normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone='')


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_alter_flat_owner_pure_phone"),
    ]

    operations = [
        migrations.RunPython(
            normalize_phone_numbers,
            reverse_normalize_phone_numbers,
        ),
    ]
