# Generated by Django 5.2.4 on 2025-07-12 09:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0012_auto_20250710_1955"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ФИО собственника"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "pure_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Нормализованный номер телефона",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flat",
            name="owners",
            field=models.ManyToManyField(
                blank=True, related_name="flats", to="property.owner"
            ),
        ),
    ]
