# Generated by Django 5.2.4 on 2025-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0013_owner_flat_owners"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={
                "verbose_name": "Собственник",
                "verbose_name_plural": "Собственники",
            },
        ),
        migrations.AlterField(
            model_name="flat",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="flats",
                to="property.owner",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
