# Generated by Django 5.2.4 on 2025-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0014_alter_owner_options_alter_flat_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="owned_flats",
            field=models.ManyToManyField(
                blank=True,
                related_name="property_owners",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
