# Generated by Django 5.2.4 on 2025-07-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0016_auto_20250712_1643"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="flat",
            field=models.ForeignKey(
                help_text="Квартира, на которую пожаловались:",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="property.flat",
                verbose_name="Квартира",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, подавший жалобу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
